### ISSUE TITLE
Typos in Dockerfile

### ISSUE THREAD

**Issue by bmv234** [woa7/docker-piler#1]
In the Dockerfile line 25 is missing a backslash at the end:

When I run the original Dockerfile I get the following error:

Error response from daemon: Dockerfile parse error line 26: unknown instruction: PACKAGE="${PACKAGE:-PILER_1.3.6~BIONIC-78E5A44_AMD64.DEB}"

Line 25 is missing a backslash at the end when the backslash is added this error is resolved.

The backslashes on lines 57 and 61 should be at the end of the previous lines:

Error response from daemon: Dockerfile parse error line 57: unknown instruction: \

I still has issues with the curl commands executing:

/bin/sh: 1: Syntax error: Unterminated quoted string
The command '/bin/sh -c curl -fSLO "${SPHINX_BIN_TARGZ}" "${SPHINX_BIN_TARGZ_DOWNLOAD_URL}"     && echo "$SPHINX_BIN_TARGZ_DOWNLOAD_SHA256 *$SPHINX_BIN_TARGZ" | sha256sum -c - || echo "sha256sum FAILD: ${SPHINX_BIN_TARGZ_DOWNLOAD_URL}"     should $SPHINX_BIN_TARGZ_DOWNLOAD_SHA256 but is:" ; sha256sum $SPHINX_BIN_TARGZ' returned a non-zero code: 2

 So I just manually entered the URLs as follows:

RUN curl -fSLO "https://download.mailpiler.com/generic-local/sphinx-3.1.1-bin.tar.gz"
RUN curl -fSLO "https://bitbucket.org/jsuto/piler/downloads/piler_1.3.6~bionic-78e5a44_amd64.deb"

**Comment by woa7** [comment]
thanks for the feadback,

i pushed some fixes, cann you try it, if it work also for you?

**Comment by bmv234** [comment]
Dockerfile issues resolved. Thank you
